=== willblend/CACM/public/google.dtd
<!ELEMENT GSP (((TM, Q, PARAM+, CB*, CT?, LOCALQUERY?,
                 TT?, CAT*, GM*, ISURL?, RPB?, BPB?, Spelling?, RelatedSearches?,
                 Synonyms?, NEWS*, MAPS?, DICTIONARY*, STOCK*, LOCAL_LISTINGS?, 
		 FROOGLE_LISTINGS?, ADS?, RES?) | CACHE | ERROR))>
<!ATTLIST GSP VER CDATA #REQUIRED>
<!ELEMENT ERROR (#PCDATA)>
<!ELEMENT TM (#PCDATA)>
<!ELEMENT Q (#PCDATA)>
<!ELEMENT CACHE (CACHE_URL, 
                 CACHE_REDIR_URL, 
                 CACHE_LAST_MODIFIED, 
                 CACHE_LEGEND_FOUND, 
                 CACHE_LEGEND_NOTFOUND, 
                 CACHE_CONTENT_TYPE, 
                 CACHE_LANGUAGE, 
                 CACHE_ENCODING, 
                 CACHE_HTML)>
<!ELEMENT CACHE_URL (#PCDATA)>
<!ELEMENT CACHE_REDIR_URL (#PCDATA)>
<!ELEMENT CACHE_LAST_MODIFIED (#PCDATA)>
<!ELEMENT CACHE_LEGEND_FOUND (CACHE_LEGEND_TEXT*)>
<!ELEMENT CACHE_LEGEND_TEXT (BLOB)>
<!ATTLIST CACHE_LEGEND_TEXT fgcolor CDATA #REQUIRED
                            bgcolor CDATA #REQUIRED>
<!ELEMENT CACHE_LEGEND_NOTFOUND (BLOB?)>
<!ELEMENT CACHE_CONTENT_TYPE (#PCDATA)>
<!ELEMENT CACHE_LANGUAGE (#PCDATA)>
<!ELEMENT CACHE_ENCODING (#PCDATA)>
<!ELEMENT CACHE_HTML (BLOB?)>
<!ELEMENT BLOB (#PCDATA)>
<!ATTLIST BLOB encoding CDATA #REQUIRED>
<!ELEMENT PARAM EMPTY>
<!ATTLIST PARAM name CDATA #REQUIRED
                value CDATA #REQUIRED
                original_value CDATA #REQUIRED>
<!ELEMENT CB (CS+)>
<!ATTLIST CB name CDATA #REQUIRED>
<!ELEMENT CS (CS*)>
<!ATTLIST CS name CDATA #REQUIRED>
<!ELEMENT CT (#PCDATA)>
<!ELEMENT TT (#PCDATA)>
<!ELEMENT GM (GL, GD?)>
<!ELEMENT GL (#PCDATA)>
<!ELEMENT GD (#PCDATA)>
<!ELEMENT ISURL EMPTY>
<!ELEMENT RPB EMPTY>
<!ELEMENT BPB EMPTY>
<!ELEMENT Spelling (Suggestion+)>
<!ELEMENT Suggestion (#PCDATA)>
<!ATTLIST Suggestion q CDATA #REQUIRED>
<!ELEMENT RelatedSearches (RelatedSearch+)>
<!ELEMENT RelatedSearch (#PCDATA)>
<!ELEMENT Synonyms (OneSynonym+)>
<!ELEMENT OneSynonym (#PCDATA)>
<!ATTLIST OneSynonym q CDATA #REQUIRED>
<!ELEMENT NEWS (U, T, SOURCE, DATE)>
<!ELEMENT SOURCE (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT MAPS (T, MAP*)>
<!ELEMENT MAP (U, SOURCE)>
<!ELEMENT STOCK (U, TICKER, COMPANYNAME)>
<!ELEMENT TICKER (#PCDATA)>
<!ELEMENT COMPANYNAME (#PCDATA)>
<!ELEMENT DICTIONARY (U, WORD?)>
<!ELEMENT WORD (#PCDATA)>
<!ELEMENT LOCAL_LISTINGS (T, U, LOCAL_LISTING*)>
<!ELEMENT LOCAL_LISTING (T, U?, ADDRESS?, PHONE_NUMBER?, DISTANCE_AWAY?)>
<!ELEMENT ADDRESS (#PCDATA)>
<!ELEMENT PHONE_NUMBER (#PCDATA)>
<!ELEMENT DISTANCE_AWAY (#PCDATA)>
<!ELEMENT IMAGE_THUMBS (T?, U?, IMAGE_THUMB*)>
<!ELEMENT IMAGE_THUMB (U, IMAGE_SOURCE, IMAGE_HEIGHT, IMAGE_WIDTH)>
<!ELEMENT IMAGE_SOURCE (#PCDATA)>
<!ELEMENT IMAGE_HEIGHT (#PCDATA)>
<!ELEMENT IMAGE_WIDTH (#PCDATA)>
<!ELEMENT FROOGLE_LISTINGS (ONE_FROOGLE*)>
<!ELEMENT ONE_FROOGLE (T, U, PRICE, MERCHANT)>
<!ELEMENT PRICE (#PCDATA)>
<!ELEMENT MERCHANT (#PCDATA)>
<!ELEMENT ADS (AD*)>
<!ELEMENT AD (LINE1, LINE2?, LINE3?, CPC?, WCPC?, PCPM?, REGIONNAME?, COMMERCIAL?)>
<!ATTLIST AD
    n CDATA #REQUIRED
    type CDATA #REQUIRED
    url CDATA #REQUIRED
    visible_url CDATA #REQUIRED>
<!ELEMENT LINE1 (#PCDATA)>
<!ELEMENT LINE2 (#PCDATA)>
<!ELEMENT LINE3 (#PCDATA)>
<!ELEMENT CPC (#PCDATA)>
<!ELEMENT WCPC (#PCDATA)>
<!ELEMENT PCPM (#PCDATA)>
<!ELEMENT REGIONNAME (#PCDATA)>
<!ELEMENT COMMERCIAL (#PCDATA)>
<!ELEMENT RES (M, FI?, XT?, NB?, MT*, R*)>
<!ATTLIST RES SN CDATA #REQUIRED
              EN CDATA #REQUIRED>
<!ELEMENT M (#PCDATA)>
<!ELEMENT FI EMPTY>
<!ELEMENT XT EMPTY>
<!ELEMENT NB (PU?, NU?)>
<!ELEMENT PU (#PCDATA)>
<!ELEMENT NU (#PCDATA)>
<!ELEMENT R (U, UE, UD?, T?, RK, LOCALINFO?, CRAWLDATE?, FS?, MT*, F*, S?, LANG?, HAS, HN?, STOCK?)>
<!ATTLIST R N CDATA #REQUIRED
            L CDATA "1"
            MIME CDATA "text/html">
<!ELEMENT U (#PCDATA)>
<!ELEMENT UE (#PCDATA)>
<!ELEMENT UD (#PCDATA)>
<!ELEMENT T (#PCDATA)>
<!ELEMENT RK (#PCDATA)>
<!ELEMENT LOCALINFO (LATLNG_PARAM, BN?, PH?, ADDR?, CITYSTATE?, ZIP?, LATITUDE, LONGITUDE)>
<!ELEMENT LOCALQUERY (ADDR?, CITYSTATE?, ZIP?, LATITUDE, LONGITUDE, RADIUS)>
<!ELEMENT LATLNG_PARAM (#PCDATA)>
<!ELEMENT BN (#PCDATA)>
<!ELEMENT PH (#PCDATA)>
<!ELEMENT ADDR (#PCDATA)>
<!ELEMENT CITYSTATE (#PCDATA)>
<!ELEMENT ZIP (#PCDATA)>
<!ELEMENT LATITUDE (#PCDATA)>
<!ELEMENT LONGITUDE (#PCDATA)>
<!ELEMENT RADIUS (#PCDATA)>
<!ELEMENT CRAWLDATE (#PCDATA)>
<!ELEMENT XP (#PCDATA)>
<!ELEMENT FS EMPTY>
<!ATTLIST FS NAME CDATA #REQUIRED
             VALUE CDATA #REQUIRED>
<!ELEMENT F  (#PCDATA)>
<!ELEMENT S  (#PCDATA)>
<!ELEMENT LANG (#PCDATA)>
<!ELEMENT HAS (DI?, L?, C?, RT?, PERS_CATS?, DEBUG?)>
<!ELEMENT DEBUG (IDX_DEBUG?, DOC_DEBUG?)>
<!ELEMENT IDX_DEBUG (#PCDATA)>
<!ELEMENT DOC_DEBUG (#PCDATA)>
<!ELEMENT DI (CAT, DT?, DS?)>
<!ELEMENT CAT (GN, FVN, METAC?, METACE?)>
<!ATTLIST CAT SE CDATA "ISO-8859-1">
<!ELEMENT GN (#PCDATA)>
<!ELEMENT FVN (#PCDATA)>
<!ELEMENT METAC (#PCDATA)>
<!ELEMENT METACE (#PCDATA)>
<!ELEMENT DT (#PCDATA)>
<!ELEMENT DS (#PCDATA)>
<!ELEMENT L EMPTY>
<!ATTLIST L TAG CDATA "link:">
<!ELEMENT C EMPTY>
<!ATTLIST C TAG CDATA "cache:"
            SZ  CDATA #REQUIRED
            ENC CDATA ""
            CID CDATA "">
<!ELEMENT RT EMPTY>
<!ATTLIST RT TAG CDATA "related:">
<!ELEMENT PERS_CATS (#PCDATA)>
<!ATTLIST HN U CDATA #REQUIRED>
<!ELEMENT HN (#PCDATA)>
<!ELEMENT MT EMPTY>
<!ATTLIST MT N CDATA #REQUIRED
             V CDATA #REQUIRED>

=== willblend/CACM/public/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GSP SYSTEM "google.dtd">
<GSP VER="3.2">
<TM>0.240534</TM><Q>cacm</Q>
<PARAM name="access" value="p" original_value="p"/>
<PARAM name="entqr" value="0" original_value="0"/>
<PARAM name="getfields" value="author.date" original_value="author.date"/>
<PARAM name="output" value="xml" original_value="xml"/>
<PARAM name="sort" value="date:D:L:d1" original_value="date%3AD%3AL%3Ad1"/>
<PARAM name="entsp" value="0" original_value="0"/>
<PARAM name="ie" value="UTF-8" original_value="UTF-8"/>
<PARAM name="client" value="cacmdp_frontend" original_value="cacmdp_frontend"/>
<PARAM name="submit.x" value="0" original_value="0"/>
<PARAM name="q" value="cacm" original_value="cacm"/>
<PARAM name="submit.y" value="0" original_value="0"/>
<PARAM name="oe" value="UTF-8" original_value="UTF-8"/>
<PARAM name="ip" value="199.68.56.230" original_value="199.68.56.230"/>
<RES SN="1" EN="10">
<M>94500</M>
<FI/><NB><NU>/search?q=cacm&amp;hl=en&amp;lr=&amp;ie=UTF-8&amp;output=xml&amp;client=cacmdp_frontend&amp;access=p&amp;sort=date:D:L:d1&amp;getfields=author.date&amp;start=10&amp;sa=N</NU>
</NB>

<R N="1"><U>http://cacm.acm.org/opinion/interviews</U><UE>http://cacm.acm.org/opinion/interviews</UE><T>Interviews | Communications of the ACM</T><RK>10</RK><FS NAME="date" VALUE="2011-03-24"/><S>Interviews. RSSRSS icon. &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
<R N="2"><U>http://cacm.acm.org/blogs/blog-cacm/103605-works-in-progress-mia</U><UE>http://cacm.acm.org/blogs/blog-cacm/103605-works-in-progress-mia</UE><T>Works in Progress: MIA | blog@&lt;b&gt;CACM&lt;/b&gt; | Communications of the ACM</T><RK>9</RK><FS NAME="date" VALUE="2011-01-05"/><MT N="author" V="Daniel Reed"/><MT N="date" V="2011-01-05"/><S>BLOG@&lt;b&gt;CACM&lt;/b&gt;. Works in Progress: MIA. Daniel Reed. January 5, 2011. &lt;b&gt;...&lt;/b&gt; (See Moshe’s &lt;b&gt;CACM&lt;/b&gt;&lt;br&gt; editorial, Conferences vs. Journals in Computing Researchfor his perspective.) &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
<R N="3" L="2"><U>http://cacm.acm.org/blogs/blog-cacm/104694-design-functionality-and-diffusion-of-innovations</U><UE>http://cacm.acm.org/blogs/blog-cacm/104694-design-functionality-and-diffusion-of-innovations</UE><T>Design, Functionality, and Diffusion of Innovations | blog@&lt;b&gt;CACM&lt;/b&gt; &lt;b&gt;...&lt;/b&gt;</T><RK>9</RK><FS NAME="date" VALUE="2011-02-06"/><MT N="author" V="Jason Hong"/><MT N="date" V="2011-02-06"/><S>BLOG@&lt;b&gt;CACM&lt;/b&gt;. &lt;b&gt;...&lt;/b&gt; Jason Hong. February 6, 2011. A few months ago, I wrote two &lt;b&gt;CACM&lt;/b&gt; blog&lt;br&gt; entries examining why great design is so hard (here and here). &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS><HN U="cacm.acm.org/blogs/blog-cacm">cacm.acm.org/blogs/blog-cacm</HN></R>
<R N="4"><U>http://cacm.acm.org/blogs/blog-cacm/102624-were-too-late-for-first-in-cs1/fulltext</U><UE>http://cacm.acm.org/blogs/blog-cacm/102624-were-too-late-for-first-in-cs1/fulltext</UE><T>We&amp;#39;re too Late for &amp;quot;First&amp;quot; in CS1 | blog@&lt;b&gt;CACM&lt;/b&gt; | Communications of &lt;b&gt;...&lt;/b&gt;</T><RK>9</RK><FS NAME="date" VALUE="2010-12-07"/><MT N="author" V="Mark Guzdial"/><MT N="date" V="2010-12-07"/><S>BLOG@&lt;b&gt;CACM&lt;/b&gt;. We&amp;#39;re too Late for &amp;quot;First&amp;quot; in CS1. Mark Guzdial. December 7, 2010.&lt;br&gt; Georgia Institute of Technology professor Mark Guzdial. &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
<R N="5"><U>http://cacm.acm.org/blogs/blog-cacm/96476-why-is-great-design-so-hard/fulltext</U><UE>http://cacm.acm.org/blogs/blog-cacm/96476-why-is-great-design-so-hard/fulltext</UE><T>Why is Great Design so Hard? | blog@&lt;b&gt;CACM&lt;/b&gt; | Communications of the &lt;b&gt;...&lt;/b&gt;</T><RK>9</RK><FS NAME="date" VALUE="2010-07-21"/><MT N="author" V="Jason Hong"/><MT N="date" V="2010-07-21"/><S>BLOG@&lt;b&gt;CACM&lt;/b&gt;. Why is Great Design so Hard? Jason Hong. July 21, 2010. I want to take&lt;br&gt; a slight detour from usable privacy and security and discuss issues of design. &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
<R N="6"><U>http://cacm.acm.org/news/49494-robert-l-ashenhurst-former-communications-editor-in-chief-dies</U><UE>http://cacm.acm.org/news/49494-robert-l-ashenhurst-former-communications-editor-in-chief-dies</UE><T>Robert L. Ashenhurst, Former Communications Editor-in-Chief, Dies &lt;b&gt;...&lt;/b&gt;</T><RK>5</RK><FS NAME="date" VALUE="2009-10-27"/><MT N="author" V="CACM Staff"/><MT N="date" V="2009-10-27"/><S>ACM News. Robert L. Ashenhurst, Former Communications Editor-in-Chief, Dies.&lt;br&gt; &lt;b&gt;CACM&lt;/b&gt; Staff. October 27, 2009. Robert L. Ashenhurst, 1929 &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
<R N="7" L="2"><U>http://cacm.acm.org/news/43680-researchers-break-vanish-security-system</U><UE>http://cacm.acm.org/news/43680-researchers-break-vanish-security-system</UE><T>Researchers Break Vanish Security System | News | Communications &lt;b&gt;...&lt;/b&gt;</T><RK>5</RK><FS NAME="date" VALUE="2009-09-30"/><MT N="author" V="CACM Staff"/><MT N="date" V="2009-09-30"/><S>ACM News. Researchers Break Vanish Security System. &lt;b&gt;CACM&lt;/b&gt; Staff. September 30, 2009.&lt;br&gt; &amp;quot;The attack was actually rather straightforward,&amp;quot; Assistant &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS><HN U="cacm.acm.org/news">cacm.acm.org/news</HN></R>
<R N="8"><U>http://cacm.acm.org/opinion/articles/101620-im-not-a-real-scientist-and-thats-okay</U><UE>http://cacm.acm.org/opinion/articles/101620-im-not-a-real-scientist-and-thats-okay</UE><T>I&amp;#39;m Not a Real Scientist, and That&amp;#39;s Okay | Opinion &lt;b&gt;...&lt;/b&gt;</T><RK>4</RK><FS NAME="date" VALUE="2010-11-12"/><MT N="author" V="Scientific American"/><MT N="date" V="2010-11-12"/><S>&lt;b&gt;...&lt;/b&gt; I Read an article in ACM Magazine (&lt;b&gt;CACM&lt;/b&gt; , issue March 2009) by Peter J.Denning and&lt;br&gt; Richard D.Riehle ; in which they are -too- complaining that: &amp;quot;software &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
<R N="9" L="2"><U>http://cacm.acm.org/opinion/articles/79237-harnessing-the-power-of-the-real-time-social-web</U><UE>http://cacm.acm.org/opinion/articles/79237-harnessing-the-power-of-the-real-time-social-web</UE><T>Harnessing the Power of the Real-Time Social Web | Opinion &lt;b&gt;...&lt;/b&gt;</T><RK>4</RK><FS NAME="date" VALUE="2010-03-09"/><MT N="author" V="By Riley Crane"/><MT N="date" V="2010-03-09"/><S>&lt;b&gt;...&lt;/b&gt; all. (For an account of the DARPA Network Challenge by a member of another&lt;br&gt; team, see the BLOG@&lt;b&gt;CACM&lt;/b&gt; series by Ethan Trewhitt—Ed.). &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS><HN U="cacm.acm.org/opinion/articles">cacm.acm.org/opinion/articles</HN></R>
<R N="10"><U>http://cacm.acm.org/careers/79686-emotional-computer-tutor-improves-girls-math-scores</U><UE>http://cacm.acm.org/careers/79686-emotional-computer-tutor-improves-girls-math-scores</UE><T>Emotional Computer Tutor Improves Girls&amp;#39; Math Scores | Careers &lt;b&gt;...&lt;/b&gt;</T><RK>3</RK><FS NAME="date" VALUE="2010-03-11"/><MT N="author" V="University of Massachusetts Amherst"/><MT N="date" V="2010-03-11"/><S>ACM News. Emotional Computer Tutor Improves Girls&amp;#39; Math Scores. University&lt;br&gt; of Massachusetts Amherst. March 11, 2010. Wayang Outpost &lt;b&gt;...&lt;/b&gt;  </S><LANG>en</LANG><HAS><L/></HAS></R>
</RES>
</GSP>
